# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-16 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Brand', models.CharField(default='eGroc', max_length=100)),
                ('Cate', models.CharField(max_length=100)),
                ('Desc', models.CharField(max_length=500)),
                ('Qty', models.IntegerField(default=99)),
                ('Prize', models.IntegerField()),
                ('Img', models.ImageField(default='', upload_to=b'')),
                ('Store', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
