# Generated by Django 3.1.5 on 2021-04-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('displayName', models.CharField(max_length=100)),
                ('Img', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='Img',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
