# Generated by Django 3.1.5 on 2021-04-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_auto_20210429_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Cate',
            field=models.CharField(choices=[('Body care', 'badyCare'), ('Kitchen ware', 'kitchen')], max_length=100),
        ),
    ]
