# Generated by Django 3.1.5 on 2021-04-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_auto_20210429_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Cate',
            field=models.CharField(choices=[('badyCare', 'Body care'), ('kitchen', 'Kitchen ware')], max_length=100),
        ),
    ]
