# Generated by Django 3.1.5 on 2021-05-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0007_auto_20210502_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('Id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('ItemDetail', models.CharField(default='', max_length=5000)),
                ('ordName', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AddField(
            model_name='category',
            name='Id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
