# Generated by Django 3.1.5 on 2021-05-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ItemDetail',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
