# Generated by Django 3.1.5 on 2021-05-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0008_auto_20210510_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Id',
            new_name='cId',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Id',
            new_name='oId',
        ),
    ]
