# Generated by Django 3.1.5 on 2021-05-10 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0009_auto_20210510_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cId',
            new_name='Id',
        ),
    ]
