# Generated by Django 3.1.5 on 2021-05-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0009_order_itemdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Id',
            new_name='ordId',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Name',
            new_name='ordName',
        ),
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AddField(
            model_name='category',
            name='catId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
