# Generated by Django 3.1.5 on 2021-05-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0010_auto_20210508_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catId',
            new_name='Id',
        ),
    ]
