# Generated by Django 3.1.5 on 2021-05-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0011_auto_20210511_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
