# Generated by Django 3.1.5 on 2021-05-09 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0012_auto_20210509_1147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders',
        ),
    ]
