# Generated by Django 3.1.5 on 2021-05-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0013_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ItemDetail', models.CharField(default='', max_length=5000)),
                ('ordName', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
            ],
        ),
    ]
