# Generated by Django 3.1.5 on 2021-05-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0014_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Id',
        ),
        migrations.AlterField(
            model_name='category',
            name='cateName',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
