# Generated by Django 3.1.5 on 2021-05-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0015_auto_20210516_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('storeName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('displayStoreName', models.CharField(max_length=100)),
                ('storeImg', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
