# Generated by Django 3.1.5 on 2021-05-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0016_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Store',
            field=models.CharField(choices=[('hansuGS', 'Hansu General Store'), ('santuGS', 'Santu General Store')], default='', max_length=100),
        ),
    ]
